# Generated by Django 4.2.6 on 2023-10-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataitem",
            name="value",
            field=models.PositiveSmallIntegerField(default=20),
            preserve_default=False,
        ),
    ]
